# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLandmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.HubDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hublandmark',
            name='landmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Landmark'),
        ),
    ]
