# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20160519_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=255)),
                ('coursename', models.CharField(max_length=255)),
                ('starttime', models.DateTimeField(null='true')),
                ('endtime', models.DateTimeField(null='true')),
            ],
        ),
        migrations.AddField(
            model_name='registrationdetails',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.StudentDetails'),
        ),
    ]
