# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_delete_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=30)),
                ('coursename', models.CharField(max_length=255)),
                ('starttime', models.DateTimeField(null='true')),
                ('endtime', models.DateTimeField(null='true')),
                ('day', models.CharField(max_length=30)),
            ],
        ),
    ]
