# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubdetails',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='hublandmark',
            name='landmarkname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
