# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20160519_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdetails',
            old_name='rollno',
            new_name='student',
        ),
    ]
