# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_auto_20160519_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseno', models.CharField(max_length=255)),
                ('coursename', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='registrationdetails',
            name='courseno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.Course'),
        ),
    ]
