# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20160519_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='endtime',
            field=models.TimeField(null='true'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='starttime',
            field=models.TimeField(null='true'),
        ),
    ]
