# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_auto_20160519_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdetails',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
