# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_hubcycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubcycle',
            name='hubid',
        ),
        migrations.DeleteModel(
            name='HubCycle',
        ),
    ]
