# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_hubcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=255)),
                ('cycleid', models.IntegerField()),
                ('fromlocation', models.CharField(max_length=255)),
                ('tolocation', models.CharField(max_length=255)),
            ],
        ),
    ]
