# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0024_hubcycle_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdetails',
            name='newavailable',
            field=models.IntegerField(default=0),
        ),
    ]
