# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_capacity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='capacity',
        ),
    ]
